version: '3.8'

services:
  users-service:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      users-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:123@users-db:5432/work_organizer_users

  users-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: work_organizer_users
    volumes:
      - users-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 3s


volumes:
  users-data:
